### ISSUE TITLE
Design Landing Page

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#1]
A landing page has to be designed.
Take examples from Wordpress templates of education business. 

Page has to be clear and precise and not cluttered.

**Comment by Akruti25** [comment]
I'll take up this one.

**Comment by imshashikantdev** [comment]
Please it to me, I am on it.

**Comment by imshashikantdev** [comment]
Hi @rajatmw1999 I have created the landing page and appended is the screenshot for the reference.

Screenshot #1
![Landing page ScreenShot 4](https://user-images.githubusercontent.com/52612360/86835765-2f67c000-c0ba-11ea-8a74-7cecc48dfb37.jpg)

Screenshot #2 
![Landing page ScreenShot 1](https://user-images.githubusercontent.com/52612360/86835098-44901f00-c0b9-11ea-93ac-28669ba20e51.JPG)

Screenshot #3 
![Landing page ScreenShot 2](https://user-images.githubusercontent.com/52612360/86835201-625d8400-c0b9-11ea-8ec1-adf8871f2f86.JPG)

Screenshot #4
![Landing page ScreenShot 3](https://user-images.githubusercontent.com/52612360/86835231-6be6ec00-c0b9-11ea-87c0-3076b9ff52a0.JPG)

**Comment by imshashikantdev** [comment]
Also, I have created a signup (Login and Registration) page.

Login page
![SignUp Login page](https://user-images.githubusercontent.com/52612360/86836459-2aefd700-c0bb-11ea-8372-ed66c71643cd.jpg)

Registration page
![SignUp Registration page](https://user-images.githubusercontent.com/52612360/86836499-37742f80-c0bb-11ea-9901-efd1af1bb95c.jpg)

**Comment by rajatmw1999** [comment]
@imshashikantdev You only needed to create the landing page designs. The signup and login are being made separately by Akruti.

Screenshot #4 looks good but still needs some improvements. We can go ahead with it

1. Add an overlay to the background image.
2. Make the text bolder and use a different font. Refer to different landing pages over the internet or in different free templates and see which one suits best.

The first slider when the website opens should be #4. The next should be #2. That's all.
Also, don't work on signup and login, the navbar, both of them are being made separately.

In this landing page, when we scroll down there will be a section of testimonials. Try to make it very catchy and professional. Using the same yellow, white etc colors that match the whole theme.
Also, above the testimonials, there will be a companies associated with us section. Where logos of the companies will be displayed like the way you must have seen in some websites in "Our partner company" sections.

Also, go to cars24.com and see the section which contains color cards in red, green, blue, purple. The section is #SafetyHands. It is the second section on cars24.com .  We will need to make a similar section of 5 cards where we will display our steps. Also include some illustration images as in cars24.com

You can create the PR after making these changes.

After these changes are done, make a folder named "Landing Page" in the front-end folder and put all your files in that folder and make the PR.
Any doubts? You know where to reach me ;)
