### ISSUE TITLE
Scrap data with Udemy

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#14]
Provided a particular URL of a Udemy page

Scrap the complete page and only display the useful content to the user.

Scrap the content of each course that appears and display it on the front end.

For example, in the URL provided above, you will scrap the whole page but only keep the useful data, that Is, all the courses displayed on that page.

**Comment by StrangerZiokan** [comment]
I will try to do this

**Comment by Ayush23Dash** [comment]
I will do this!
