### ISSUE TITLE
Design a responsive navbar

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#15]
Design a responsive and good looking navbar in a completely separate file from the existing files. Add unique styles to each element using their ids and not their tags.
Use dummy links for the navbar for now and dummy brand logo.

The navbar should be responsive for mobile(using a burger icon). Refer to other websites or existing navbar codes on other websites like colorlib if necessary.

Also, include a screeenshot in the pr of the designed navbar, so I can review it there only.

**Comment by Akruti25** [comment]
I'll take up this one.
