### ISSUE TITLE
Design a responsive footer

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#16]
Design a responsive and good looking fiiter in a completely separate file from the existing files. Add unique styles to each element using their ids and not their tags.
Use dummy links for the navbar for now and dummy brand logo.

The footer should be responsive for mobile. Refer to other websites or existing navbar codes on other websites like colorlib if necessary.

Also, include a screenshot in the pr of the designed footer, so I can review it there only.

**Comment by coastaldemigod** [comment]
I'll do it.
