### ISSUE TITLE
Aniket - Code the Numbers Section.

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#162]
https://codepen.io/caplock221b/pen/WNraREK/

The above link contains a numbers section for our landing page. You have to make the following changes to it.

1. The designs applied in the CSS file have to be changed to custom CSS. For example, if some designs are applied to body or container or h1, change all of these designs to custom CSS classes whose name will be "yourname_componentname". This way the designs will not conflict with other files.
**_For e.g._**, 
`<h1> This is my component </h1>`

h1{
color: red;
}

**_will change to_**
 
`<h1 class="aniket_numbers_section">This is my component</h1>`

.aniket_numbers_section{
color: red;
}

 -------------------------------------------------------
This way the style will be unique and won't conflict with others. Change all the CSS styles this way.

2. Once it is done. Make a new folder in the "front-end" folder after your component and put the CSS and HTML file there and make the PR.

 Don't forget to include a screenshot of the mobile and desktop version both.
The deadline is the 18th Evening.

**Comment by aniket-sinha8** [comment]
In this work, I just need to change to custom CSS with class name as yourname_componentname. No change in any other thing right!
