### ISSUE TITLE
Plural Sight API

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#17]
Pluralsight.com provides an API to fetch data about their courses.

Read the docs of their API and make an API request for the information of a particular technology(like NodeJS, HTML, Android, etc). Return the data obtained from the PluralSight API in a proper format.

Make call to PluralSight API with a particular query string obtained from the user.
Take the data returned from PluralSight API and make it in a particular format.
Return the data to the user in JSON format.

**Comment by NirojDeb** [comment]
Will try to do this.
