### ISSUE TITLE
Aradhna - Design Card Component - BetaPage

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#2]
Make use of the image provided in assets **'betapage-card.png'** and design a similar card component in ReactJS.

The image is taken from the website **betapage.co** . You can refer to the website.

The card component will be used to display the course content, like the author, rating, etc.

Dont forget to include the screenshots in the "front-end/--SCREENSHOTS" folder while making the PR so it easier to review.

**Comment by imshashikantdev** [comment]
Please assign it to me. I am on it.

**Comment by aradhna7** [comment]
Done
