### ISSUE TITLE
Shivam - Changes in routes

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#212]
1. api/data_routes/index.js

#Route1
(a). Take the name of skill in req.params.skillName. The word will be separated by '-'. 
For example, if req.params.skillName = 'databases', then use it as it is.
If req.params.skillName='computer-science', then, seperate it into 'computer' and 'science' and search in db for skills that contains(include and not exact match) 'computer' and 'science' in the skillName.

(b). The platform is not being returned along with the array object. Also, return the platforms along with the array of courses, we can directly know which platform is used for that course.
(c). All data contains weird  **/"**  in the starting and the end of their values.

#Route3
(a). Instead of searching for a particular course name, search for a particular object id instead. You will be given skillName and objectid of the course. Search that objectid in the mentioned skill and return that course.
#Route4
(a). It is returning "Not Found.".

**Try to do it before evening of 4th September. After that, we will test it and see if any further changes are required.**

**Comment by rajatmw1999** [comment]
@shivam7374 I was thinking of having a AND condition in "computer-science", i.e, both computer and science should be present. Can you make another route for AND condition also. 
Let the current OR route be there.

**Comment by shivam7374** [comment]
Okay @rajatmw1999  I will try to deal with the AND condition and make a separate route for this.

**Comment by shivam7374** [comment]
Made the route for the AND condition.
