### ISSUE TITLE
Aradhna - Design the filter box

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#22]
As shown in the image 'filter-component' in the assets folder, design a filter box with various options as shown in the screenshot. The link it is taken from is: https://classpert.com/angularjs

Code exactly the same type of filter box. It should be responsive and only take that much width of the page. 

Apart from the price bar in the filter box, also add a "number of hours" bar where user will be able to select the number of hours of the course.

Don't forget to include the screenshots in the PR.

**Comment by DauntingDruid** [comment]
assign this to me I'll do it

**Comment by rajatmw1999** [comment]
@DauntingDruid  please let me know your name. Also, the deadline for submitting the PR is monday.

**Comment by DauntingDruid** [comment]
@DauntingDruid is Abhishek Tomar
