### ISSUE TITLE
Design the about section

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#23]
As shown in the image 'about-section.PNG' in assets folder, design the about section that will come exactly below the header navbar and will contain some information about the page.

DO NOT design a navbar, that is being made separately. 

1. You can include a background image as well and add an overlay on it.
2. The heading font and color should be bigger and more prominent than the subtext.

https://classpert.com/computer-science

**Comment by imshashikantdev** [comment]
On it.

**Comment by Akruti25** [comment]
I'll take this up
