### ISSUE TITLE
Design a contact us form.

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#24]
Design a contact us form with various fields like name, phone, email, subject, body, and a submit button.

The form should be good looking and responsive. Try to be creative. Take inspiration from various templates available online.
You can also add a background to the complete page and a sleek form in middle. Do whatever looks good.

Don't forget to include the output screenshot in the PR.

**Comment by imshashikantdev** [comment]
On it.

**Comment by aniket-sinha8** [comment]
Can I design this?

**Comment by rajatmw1999** [comment]
@aniket-sinha8 please go ahead with this. @imshashikantdev you can focus on the landing page for now.

**Comment by aniket-sinha8** [comment]
Done. Merge it.
