### ISSUE TITLE
Design course detail section

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#26]
Design the course detail section as shown in 'course-detail-1.PNG' in the assets folder.
Try to add your imagination and take inspiration from other designs and fonts and colors over the internet.

You can refer to the way udemy.com designs its course detail section.

Don't forget to include the screenshots in the PR.

https://classpert.com/udacity/courses/intro-to-ajax-2wZ0ys

**Comment by NirojDeb** [comment]
I will try to complete this.
