### ISSUE TITLE
Suggestions Carousel

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#27]
Design a carousel as shown in the screenshot 'suggestion-carousel.PNG' in the assets folder.

For now, just make use of simple vertical divs as elements of the carousel. Later, we will change these blank divs with the course details cards as is shown in picture. The carousel should be smooth, centered, with both arrow controls on left and right side and the circle controls on the bottom.

Don't forget to include the screenshots in the PR.

**Comment by StrangerZiokan** [comment]
Ok, I will try this
