### ISSUE TITLE
JWT auth and new user signup

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#29]
Make an authentication API whenever new user signup into our application, store the data in the user MongoDB model. Encrypt the password and make use of 'jwt' to return an encrypted string unique to that user to the front end.

Learn and read how to make authentication at backend from youtube if you don't know how to do it.

It should:
1. Take the email, name, password, etc data from the front end as a submitted form in req.body.
2. Store the data in a new user model if that phone and email do not already exist.
3. Don't forget to encrypt the password using bcryptjs or another library which is famous.
4. Make use of jwt to create a unique authentication token for that user and return it to the front end.

Note: The code should properly handle errors, return an error, and success codes(404,400,200, etc) and make use of async-await to make sure better database calls.

**Comment by StrangerZiokan** [comment]
I will try to do it
