### ISSUE TITLE
Design Card Component in React  -  HackrIO

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#3]
Make use of the image provided in assets **'hackrio-card.png'** and design a similar card component in ReactJS.

The image is taken from the website **hackr.io** . You can refer to the website.

The card component will be used to display similar information hackr.io has provided, i.e, different technologies like JAVA, C++, etc.

**Comment by aniket-sinha8** [comment]
I want to work on this. - Aniket Kumar Sinha
