### ISSUE TITLE
Akruti - Improvement in Navbar Design

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#36]
1. You can move all the links to the right instead of left. 
2. Make the height of the navbar a bit more.
3. Make the background of the navbar transparent.
4. When the navbar ends, put a hr element to denote that it has ended. 
i.e.,
<hr>
a thin line like this.

Have a look at the navbar of https://1pop.in. You will gain more clarity on the final requirement.

**Comment by Akruti25** [comment]
Got it!
