### ISSUE TITLE
Design a Search Bar

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#37]
Design a search bar. It should be rectangular in shape, but a little bit of curved border, something like the github comment box you will see below this issue.

When hover over it, i should get a very faint box-shadow and clicking on it(making it active and typing) should give a more dark box shadow. Refer to the comment box below or any other search box on other websites.

1. Make it responsive for mobile.
2. Design should be professional looking.
3. Include screenshot of normal, hovered and clicked search bar in "Screenshot of PR" folder in front-end folder.

**Comment by coastaldemigod** [comment]
I'll do this , Shivansh here

**Comment by rajatmw1999** [comment]
Please go ahead.

**Comment by coastaldemigod** [comment]
Shouldn't the search bar be integerated in the navbar , instead of it standing alone

**Comment by rajatmw1999** [comment]
It will be present in the landing home page as stand alone.
And when users goes to some other page, it will then be used in the navbar.
