### ISSUE TITLE
Shivansh - Design a testimonials section

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#47]
A testimonials section has to be designed.

1. Please do some research and look at some good designs online. Find the best ones that look professional and different from primitive sliders and use them.
2. Should include image of person, name of person, designation of person and their review.
3. Try to make it dynamic and animative. 

Dont forget to include the screenshots in the "front-end/--SCREENSHOTS" folder while making the PR.

**Comment by coastaldemigod** [comment]
Done .
