### ISSUE TITLE
Create API route for YOUTUBE

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#6]
Youtube.com provides an API to fetch data about their courses.

Read the docs of their API and make an API request for the information of a particular technology(like NodeJS, HTML, Android, etc). Return the data obtained from the youtube API in a proper format.

1. Make a call to youtube API with a particular query string obtained from the user.
2. Take the data returned from youtube API and make it in a particular format.
3. Return the data to the user in JSON format.

**Comment by StrangerZiokan** [comment]
Shikhar Here, Will try to do this part.
