### ISSUE TITLE
Scrap data from Coursera

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#7]
Provided a particular URL of a Coursera page(like this - _https://www.coursera.org/search?query=web%20development&skipBrowseRedirect=true_)

Scrap the complete page and only display the useful content to the user.

Scrap the content of each course that appears and display it on the front end.

For example, in the URL provided above, you will scrap the whole page but only keep the useful data, that Is, all the courses displayed on that page.

**Comment by Ayush23Dash** [comment]
I will try and do this!
