### ISSUE TITLE
Aradhna - Make the Card-Hackrio Component

### ISSUE THREAD

**Issue by rajatmw1999** [rajatmw1999/thisCourse#84]
You will find a "Card-hackrio" component in the front-end folder. 
![hackrio-card](https://user-images.githubusercontent.com/43850934/88225171-b8205780-cc87-11ea-8001-36dd40953de7.PNG)

It looks like the above image, although there are some problems.

1. Not good on mobile screen.
2. The whole arrangement is not in the middle of the screen.
3. Size of all cards are not same. Some are overflowing due to the image logo size or too much text.
4. Padding is also not that good.

You know what to do )
Don't forget to drop a ss in the PR..

**Comment by aradhna7** [comment]
Done!
