### ISSUE TITLE
Shashikant- Improvement in About Section

### ISSUE THREAD

**Issue by aradhna7** [rajatmw1999/thisCourse#91]
In the about-section component in frontend  folder do the following changes:
1. The section is too wide. Make sure to make it of height equal to the height of about section in about-section.png in assets folder.
2. Remove the extra space below A-Z part.
3. Try some professional font for heading and subheading.

Don't forget to drop a screenshot in the PR.

**Comment by imshashikantdev** [comment]
@aradhna7, Current about section is not responsive as well, see below screenshot.
![image](https://user-images.githubusercontent.com/52612360/88761373-a3165d80-d18c-11ea-972a-3d4a845dd851.png)

**Comment by aradhna7** [comment]
It is responsive. Make sure you have pulled latest changes from repo.

![aboutmobile](https://user-images.githubusercontent.com/51862190/88763489-d8bd4580-d190-11ea-9980-28c751b62f72.PNG)
