### ISSUE TITLE
Vanshika- Improvement in Header with Search Bar

### ISSUE THREAD

**Issue by aradhna7** [rajatmw1999/thisCourse#92]
In the improved search+nav folder in frontend component folder do the following changes:

1. Desktop view is perfect. Don't change anything in that.
2.  In mobile view search bar is not aligned properly. So align it with other header components to the left.
3.  In ipad size screen, search is merging with header components. Fix that
![search+nav](https://user-images.githubusercontent.com/51862190/88637611-04c8c000-d0d8-11ea-9276-49302f1825ec.PNG)

4. Also in small size screen, after opening header components, close button is not working. So fix that.

Don't forget to drop a screenshot in the PR.

**Comment by VanshikaGahlawat** [comment]
<img width="441" alt="Screenshot 2020-07-28 at 16 25 42" src="https://user-images.githubusercontent.com/50677581/88676594-e2e83100-d109-11ea-83cd-b30e0c70c728.png">
ipad issue👆
<img width="441" alt="Screenshot 2020-07-28 at 16 25 59" src="https://user-images.githubusercontent.com/50677581/88676615-ec719900-d109-11ea-8420-897bdcb2e626.png">
search bar and navbar toggle issue 👆
